name: Check Format
on:
  push:
  pull_request:
      branches:
        - main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 20.x
      
      - name: Install 🔧 # Install dependencies
        run: |
          npm install
      
      - name: Check Format
        run: |
          npm run check-format
          npm run prettier --write .

